# Generated by Django 5.1.6 on 2025-03-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('BRAZIL', 'Brasil'), ('Estados Unidos', 'USA'), ('ESPANHA', 'Espanha'), ('CANADA', 'Canadá')], max_length=100)),
            ],
        ),
    ]
