# Generated by Django 5.1.6 on 2025-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('BRAZIL', 'Brasil'), ('Estados Unidos', 'USA'), ('Espanha', 'ESPANHA'), ('Canadá', 'CANADA')], max_length=100),
        ),
    ]
