# Generated by Django 5.1.6 on 2025-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('BRAZIL', 'Brasil'), ('Estados Unidos', 'USA'), ('ESPANHA', 'Espanha'), ('Canadá', 'CANADA')], max_length=100),
        ),
    ]
